### ISSUE TITLE
Produce medias meta presentation

### ISSUE THREAD

**Issue by mathieuLivebardon** [VCityTeam/UD-Imuv#215]
- [x] Contact A. (communication manager of IMU)
- [ ] Produce video / audio 
- [ ] Integrate in game
- [ ] Enjoy

**Comment by mathieuLivebardon** [comment]
### Communication

Agency :

 -   A communication agency will create a 1mn 30s video spot for IMUV
 -   ACH will participate in the creation of the script for the spot

IMU Days :

- 17 et 18 November
- Be there especially on Thursday for a presentation of IMUV.

TO DO :

- Give the link of the Google Form to ACH (maybe put it on the IMUV homepage)
- Share on LinkedIn the pastille and the work of LabEx IMU
- Watch on the Metaverse (IMUV is not the Metaverse!)  https://github.com/VCityTeam/UD-Imuv/issues/244
- Add credits in the IMUV home page https://github.com/VCityTeam/UD-Imuv/issues/247
- Create an IMUV black and white icon (round) https://github.com/VCityTeam/UD-Imuv/issues/246
